Repository NREL/H2Integrate, pull requests merged in 2024-10, with the labels that each got.

#8 GreenHEART Jupyter examples
  examples/01-green-hydrogen.ipynb
  examples/02-green-steel.ipynb
  examples/03-green-ammonia.ipynb
  examples/04-PEM_electrolyzer.ipynb
  examples/inputs/floris/floris_input_lbw_6MW.yaml
  examples/inputs/plant/default_fin_config.yaml
  examples/inputs/plant/greenheart_config_onshore-ammonia.yaml
  examples/inputs/plant/greenheart_config_onshore-hydrogen.yaml
  examples/inputs/plant/greenheart_config_onshore-steel.yaml
  examples/inputs/plant/hopp_config.yaml
  examples/inputs/power_profile/renewable_power_signal.csv
  examples/inputs/turbines/lbw_6MW.yaml
  examples/inputs/weather/solar/47.5233_-92.5366_psmv3_60_2013.csv
  examples/inputs/weather/wind/47.5233_-92.5366_windtoolkit_2013_60min_100m_120m.srw
Labels: documentation, enhancement

#17 Fix the CI for the new GreenHEART repo
  examples/greenheart/05-offshore-h2/input/floris/floris_input_osw_18MW.yaml
  examples/greenheart/05-offshore-h2/input/turbines/osw_18MW.yaml
  greenheart/__init__.py
  greenheart/tools/optimization/openmdao.py
  tests/greenheart/input_files/floris/floris_input_osw_18MW.yaml
  tests/greenheart/input_files/turbines/osw_18MW.yaml
  tests/greenheart/inputs/floris_input.yaml
  tests/greenheart/test_greensteel/input/floris/floris_input_lbw_6MW.yaml
  tests/greenheart/test_greensteel/input/plant/hopp_config_mn_2030.yaml
  tests/greenheart/test_greensteel/input/plant/hopp_config_tx_2025.yaml
  tests/greenheart/test_greensteel/input/plant/hopp_config_tx_2030.yaml
  tests/greenheart/test_greensteel/input/plant/hopp_config_tx_2035.yaml
  tests/greenheart/test_greensteel/input/turbines/lbw_6MW.yaml
Labels: bug

#23 Remove unused dependencies
  pyproject.toml
Labels: enhancement

#30 Updating GreenHEART Examples
  README.md
  environment.yml
  examples/04-PEM_electrolyzer.ipynb
  examples/README.md
  examples/greenheart/05-offshore-h2/greenheart-h2-offshore.py
  examples/greenheart/05-offshore-h2/input/floris/floris_input_osw_18MW.yaml
  examples/greenheart/05-offshore-h2/input/plant/default_fin_config.yaml
  examples/greenheart/05-offshore-h2/input/plant/greenheart_config.yaml
  examples/greenheart/05-offshore-h2/input/plant/hopp_config.yaml
  examples/greenheart/05-offshore-h2/input/plant/orbit-config-osw_18MW.yaml
  examples/greenheart/05-offshore-h2/input/turbines/osw_18MW.yaml
  examples/reference_plants/03-offshore-hydrogen-gom/offshore-hydrogen-gom.py
Labels: documentation, code cleanup

#31 Add a Conda `environment.yml` for easy setup
  README.md
  docs/_toc.yml
  docs/install.md
  environment.yml
Labels: documentation, enhancement

#34 Enhancement: Log CI build environment settings
  .github/workflows/ci.yml
Labels: enhancement, low priority
